version: "3.6"
services:
  web:
    expose:
      # Storefront Hot Proxy Ports
      - 9998
      - 9999
    ports:
      # Shopware Administration Watcher (see below)
      - 9997:9997
    environment:
      # Shopware Administration Watch Host
      - HOST=0.0.0.0
      # Shopware Administration Watch Port
      - PORT=9997
      # Expose APP_URL to administration watcher
      - APP_URL=http://${DDEV_SITENAME}.ddev.site
      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,9999:9999,8888:9998
      - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,8899:9999,9998:9998
